package modelo;
// Generated Apr 8, 2019 4:54:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comentarista generated by hbm2java
 */
public class Comentarista  implements java.io.Serializable {


     private int idcomentarista;
     private String nombre;
     private String correo;
     private String contrasenia;
     private Set comentarios = new HashSet(0);

    public Comentarista() {
    }

	
    public Comentarista(int idcomentarista, String nombre, String correo, 
            String contrasenia) {
        this.idcomentarista = idcomentarista;
        this.nombre = nombre;
        this.correo = correo;
        this.contrasenia = contrasenia;
    }
    public Comentarista(int idcomentarista, String nombre, String correo, 
            String contrasenia, Set comentarios) {
       this.idcomentarista = idcomentarista;
       this.nombre = nombre;
       this.correo = correo;
       this.contrasenia = contrasenia;
       this.comentarios = comentarios;
    }
   
    public int getIdcomentarista() {
        return this.idcomentarista;
    }
    
    public void setIdcomentarista(int idcomentarista) {
        this.idcomentarista = idcomentarista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


