package modelo;
// Generated Apr 8, 2019 4:54:20 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable{

     private int idmarcador;
     private Tema tema;
     private String descripcion;
     private String datosExtra;
     private double longitud;
     private double latitud;
     private Set comentarios = new HashSet(0); //??
     private Set comentarios_1 = new HashSet(0); //??

    public Marcador() {
    }

	
    public Marcador(int idmarcador, Tema tema, String descripcion, 
            double longitud, double latitud) {
        this.idmarcador = idmarcador;
        this.tema = tema;
        this.descripcion = descripcion;
        this.longitud = longitud;
        this.latitud = latitud;
    }
    public Marcador(int idmarcador, Tema tema, String descripcion, 
            String datosExtra, double longitud, double latitud, Set comentarios, 
            Set comentarios_1) {
       this.idmarcador = idmarcador;
       this.tema = tema;
       this.descripcion = descripcion;
       this.datosExtra = datosExtra;
       this.longitud = longitud;
       this.latitud = latitud;
       this.comentarios = comentarios;
       this.comentarios_1 = comentarios_1;
    }
   
    public int getIdmarcador() {
        return this.idmarcador;
    }
    
    public void setIdmarcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDatosExtra() {
        return this.datosExtra;
    }
    
    public void setDatosExtra(String datosExtra) {
        this.datosExtra = datosExtra;
    }
    public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }
    public double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getComentarios_1() {
        return this.comentarios_1;
    }
    
    public void setComentarios_1(Set comentarios_1) {
        this.comentarios_1 = comentarios_1;
    }


}


