
package modelo;
// Generated 14/05/2019 01:28:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comentarista generated by hbm2java
 */
public class Comentarista  implements java.io.Serializable {


     private String correo;
     private String nombre;
     private String contrasenia;
     private Set comentarios = new HashSet(0);
     private Set comentarios_1 = new HashSet(0);

    public Comentarista() {
    }

	
    public Comentarista(String correo, String nombre, String contrasenia) {
        this.correo = correo;
        this.nombre = nombre;
        this.contrasenia = contrasenia;
    }
    public Comentarista(String correo, String nombre, String contrasenia, Set comentarios, Set comentarios_1) {
       this.correo = correo;
       this.nombre = nombre;
       this.contrasenia = contrasenia;
       this.comentarios = comentarios;
       this.comentarios_1 = comentarios_1;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getComentarios_1() {
        return this.comentarios_1;
    }
    
    public void setComentarios_1(Set comentarios_1) {
        this.comentarios_1 = comentarios_1;
    }




}


