package modelo;
// Generated 14/05/2019 01:28:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Tema generated by hbm2java
 */
@Entity
public class Tema implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idtema", updatable = false, nullable = false)
    private int idtema;
    private Informador informador;
    private String nombre;
    private Set marcadors = new HashSet(0);

    public Tema() {
    }

    public Tema(int idtema, Informador informador, String nombre) {
        this.idtema = idtema;
        this.informador = informador;
        this.nombre = nombre;
    }

    public Tema(Informador informador, String nombre) {
        this.informador = informador;
        this.nombre = nombre;
    }

    public Tema(int idtema, Informador informador, String nombre, Set marcadors) {
       this.idtema = idtema;
       this.informador = informador;
       this.nombre = nombre;
       this.marcadors = marcadors;
    }

    public int getIdtema() {
        return this.idtema;
    }

    public void setIdtema(int idtema) {
        this.idtema = idtema;
    }
    public Informador getInformador() {
        return this.informador;
    }

    public void setInformador(Informador informador) {
        this.informador = informador;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMarcadors() {
        return this.marcadors;
    }

    public void setMarcadors(Set marcadors) {
        this.marcadors = marcadors;
    }

}
